[docs] update README logo url, LICENSE year
EasyWebApp/WebCell pull request #22
Opened 2024-01-23 16:43 UTC by wangrunlin

2024-01-24 09:56 UTC, TechQuery requested changes

2024-01-24 09:56 UTC, TechQuery commented on License
> +版权所有（c）2019 - 2024 TechQuery
```suggestion
版权所有（C）2019 - 2024 TechQuery
```

2024-01-24 14:23 UTC, wangrunlin commented on License
> +版权所有（c）2019 - 2024 TechQuery
我复制的官方的内容，官方仓库就是小写的 c

2024-01-24 15:21 UTC, TechQuery commented on License
> +版权所有（c）2019 - 2024 TechQuery
> 我复制的官方的内容，官方仓库就是小写的 c
> https://github.com/996icu/996.ICU/blob/908c19b4517fd406bf9d567b64bcd1fe79112a7b/LICENSE_CN#L1

可能当时我就是觉得上下不对称，我就换成大写了😂

2024-01-26 13:53 UTC, TechQuery requested changes
中文更新的内容就同步到英文版

2024-01-26 13:53 UTC, TechQuery commented on ReadMe-zh.md
> +- **MarkDown 集成**: [MarkCell][50]（**MDX** 实现）
```suggestion
- **MarkDown 集成**: [Parcel MDX transformer][50]（**MDX** 编译器插件）
```
链接：https://github.com/EasyWebApp/Parcel-transformer-MDX

2024-01-30 19:28 UTC, wangrunlin commented on ReadMe-zh.md
> +| 视图渲染器 | [DOM 渲染器 2][17] | SnabbDOM |(内置)| SnabbDOM（分叉）|
这里应该是 DOM Render?

2024-01-30 21:19 UTC, TechQuery requested changes

2024-01-30 21:19 UTC, TechQuery commented on ReadMe.md
> +
```suggestion
![WebCell logo](https://web-cell.dev/WebCell-0.f9823b00.png)

# WebCell
```

2024-01-30 21:21 UTC, TechQuery commented on ReadMe-zh.md
> +| 视图渲染器 | [DOM 渲染器 2][17] | SnabbDOM |(内置)| SnabbDOM（分叉）|
> 这里应该是 DOM Render?

render 是动词，renderer 是名词：https://github.com/EasyWebApp/DOM-Renderer

2024-01-31 05:26 UTC, wangrunlin commented on ReadMe.md
> +
markdown lint 的提示，在一级标题上尽量不加上其他元素，目前此处和中文文档是同步的，需要一起修改回去吗？

2024-01-31 16:35 UTC, TechQuery approved these changes

2024-01-31 16:43 UTC, merged