[docs] update GitHub and website multilingual documentation links
EasyWebApp/WebCell pull request #25
Opened 2024-01-31 19:10 UTC by wangrunlin

- Closes #24

2024-01-31 19:34 UTC, TechQuery requested changes

2024-01-31 19:34 UTC, TechQuery commented on package.json
> +        "pack-docs-language": "mv ReadMe-zh.html docs/ && replace './ReadMe-zh.md' './ReadMe-zh.html' docs/index.html",
还有其它 Markdown 文档怎么办？我是打算用这里的插件一次性解决：https://github.com/TypeStrong/typedoc/issues/2288#issuecomment-1564318304

2024-01-31 19:37 UTC, wangrunlin commented on package.json
> +        "pack-docs-language": "mv ReadMe-zh.html docs/ && replace './ReadMe-zh.md' './ReadMe-zh.html' docs/index.html",
https://www.npmjs.com/package/@knodes/typedoc-plugin-pages#compatibility

只有 `typedoc 0.23` 可用，需要改造下，我刚才使用过这个方案，没跑起来才放弃了

2024-01-31 19:59 UTC, TechQuery commented on package.json
> +        "pack-docs-language": "mv ReadMe-zh.html docs/ && replace './ReadMe-zh.md' './ReadMe-zh.html' docs/index.html",
> https://www.npmjs.com/package/@knodes/typedoc-plugin-pages#compatibility
> 
> 只有 `typedoc 0.23` 可用，需要改造下，我刚才使用过这个方案，没跑起来才放弃了

原作者搞不过来了：KnodesCommunity/typedoc-plugins#369

2024-01-31 20:13 UTC, wangrunlin commented on package.json
> +        "pack-docs-language": "mv ReadMe-zh.html docs/ && replace './ReadMe-zh.md' './ReadMe-zh.html' docs/index.html",
已更新多语言脚本

2024-01-31 20:42 UTC, TechQuery requested changes

2024-01-31 20:42 UTC, TechQuery commented on package.json
> +        "pack-docs-language": "for file in ReadMe-*.html; do new_file=\"${file#ReadMe-}\"; mv $file docs/\"$new_file\"; replace \"./${file%.html}.md\" \"./$new_file\" docs/*.html; done",
这么长的 shell 语句还是写成独立文件好维护，文件能代码高亮、缩进。

2024-02-03 17:48 UTC, TechQuery requested changes

2024-02-03 17:48 UTC, TechQuery commented on pack-docs.sh
用 Prettier 插件格式化一下：https://www.npmjs.com/package/prettier-plugin-sh

2024-02-06 05:31 UTC, TechQuery approved these changes

2024-02-06 05:32 UTC, merged

2024-02-06 18:34 UTC, TechQuery commented on package.json
> +        "pack-docs-language": "mv ReadMe-zh.html docs/ && replace './ReadMe-zh.md' './ReadMe-zh.html' docs/index.html",
> 还有其它 Markdown 文档怎么办？

@wangrunlin 这一条其实没做啊，不符合 issue 的要求。